POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@gmail.com",
    "age":20,
    "password": "123456"
}
###

GET http://localhost:3000/users/1
Content-Type: application/json
